### ISSUE TITLE
Using asdf-vm or alternatives instead of version specific runtimes

### ISSUE THREAD

**Issue by OriR** [caarlos0/machine#40]
Hey there! 👋 
Stumbled into this by accident through your dotfiles and I love the concept!

However, I work a lot with node and tend to use different versions of node for different repositories - the older the repo, the older the node version it requires.

It would be great if instead of actually installing a specific version here
https://github.com/caarlos0/machine/blob/cc759d87f50102bd698932525bebb2d97924d73c/tasks/node.yml#L3-L6

It could instead, install something like [`asdf-vm`](https://github.com/asdf-vm/asdf) or [`nvm`](https://github.com/nvm-sh/nvm) (specifically for node) and use these to actually install a specific runtime version.

If you don't care about this kind of versioning - nothing changes, since there will always be just the one version defined in your path.
If you do care about this kind of versioning - it would add it as part of the machine setup so you would use that when needed.

**Comment by caarlos0** [comment]
hmm, this is actually pretty much outdated... I haven't been using it for a long time...

will update readmes and archive, thanks for pointing it out though, feel free to fork/copy and do what's best for your use case. :)

**Comment by OriR** [comment]
Oh... so how do you set up a new machine nowadays? 🤔

**Comment by caarlos0** [comment]
I only use mac, so I use mostly a brewfile: https://github.com/caarlos0/macos

<blockquote><img src="https://avatars1.githubusercontent.com/u/245435?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/caarlos0/macOS">caarlos0/macOS</a></strong></div><div>How I setup a new Mac. Contribute to caarlos0/macOS development by creating an account on GitHub.</div></blockquote>

**Comment by caarlos0** [comment]
closing, feel free to contact me elsewhere if you need :) (links on my profile)
